"""Queries over detection_job: managing the lifecycle and progress of uploads and tasks (FR-2.6)."""

from __future__ import annotations

import datetime as dt
from typing import Any, Final

from sqlalchemy import Select, func, select
from sqlalchemy.orm import InstrumentedAttribute

from backend.core.exceptions import ValidationError
from backend.models.detection import DetectionJob, InputType, JobStatus, utcnow
from backend.repositories.base import DEFAULT_PAGE_SIZE, BaseRepository

__all__ = ["JobRepository", "JOB_SORT_COLUMNS"]

_PROGRESS_MIN: Final[float] = 0.0
_PROGRESS_MAX: Final[float] = 1.0

JOB_SORT_COLUMNS: Final[dict[str, InstrumentedAttribute[Any]]] = {
    "created_at": DetectionJob.created_at,
    "completed_at": DetectionJob.completed_at,
    "status": DetectionJob.status,
    "input_type": DetectionJob.input_type,
    "progress": DetectionJob.progress,
    "id": DetectionJob.id,
}
"""Allowed sort columns for job queries."""


class JobRepository(BaseRepository[DetectionJob, str]):
    """Reads and writes rows of ``detection_job``.

    The primary key is a UUID string generated by the model's default, so
    :meth:`create_job` does not take an identifier -- letting a caller supply
    one would make it possible to collide with, or overwrite, an existing job.
    """

    model = DetectionJob

    # -- Create -----------------------------------------------------------

    def create_job(
        self,
        *,
        input_type: str | InputType,
        source_path: str | None = None,
        total_frames: int | None = None,
    ) -> DetectionJob:
        """Create a job in the ``pending`` state.

        ``pending`` rather than ``processing``: a video upload returns
        ``202 Accepted`` immediately while the background worker may not have
        started yet, and a job that claims to be processing before anything
        touched it is indistinguishable from one that stalled.

        Args:
            input_type: ``image``, ``video`` or ``webcam``.
            source_path: Where the uploaded file was stored, as a string. Path
                objects are converted by the caller through the settings
                object; no path is ever built from a literal here (NFR-M4).
            total_frames: Frame count for a video when it is known up front.

        Returns:
            The persisted job, flushed so its generated ``id`` is available --
            the response to the upload needs it immediately.

        Raises:
            ValidationError: If ``input_type`` is not one of the three accepted
                values. Checked here rather than relying on the table's
                ``CHECK`` constraint, which would surface as an opaque
                ``IntegrityError`` naming a constraint instead of a field.
        """
        value = str(input_type)
        if value not in set(InputType):
            raise ValidationError(
                f"Unknown input_type {value!r}",
                user_message="Loại dữ liệu đầu vào không hợp lệ.",
                context={"input_type": value},
            )
        return self.create(
            input_type=value,
            status=JobStatus.PENDING.value,
            progress=_PROGRESS_MIN,
            source_path=source_path,
            total_frames=total_frames,
            processed_frames=0,
        )

    # -- Read -------------------------------------------------------------

    def list_paginated(
        self,
        *,
        page: int = 1,
        page_size: int = DEFAULT_PAGE_SIZE,
        status: str | JobStatus | None = None,
        input_type: str | InputType | None = None,
        start_time: dt.datetime | None = None,
        end_time: dt.datetime | None = None,
        sort_by: str | None = None,
        descending: bool = True,
    ) -> tuple[list[DetectionJob], int]:
        """Return one page of jobs and the total matching count.

        Args:
            page: 1-based page number.
            page_size: Jobs per page, clamped to the repository maximum.
            status: Restrict to one lifecycle state, or ``None`` for all.
            input_type: Restrict to one input type, or ``None`` for all.
            start_time: Earliest ``created_at``, inclusive.
            end_time: Latest ``created_at``, exclusive.
            sort_by: A key of :data:`JOB_SORT_COLUMNS`; defaults to
                ``created_at``.
            descending: ``True`` returns newest first.

        Returns:
            ``(jobs on this page, total jobs matching the filters)``.

        Raises:
            ValidationError: If ``sort_by`` is not an accepted key.
        """
        stmt: Select[tuple[DetectionJob]] = select(DetectionJob)
        if status is not None:
            stmt = stmt.where(DetectionJob.status == str(status))
        if input_type is not None:
            stmt = stmt.where(DetectionJob.input_type == str(input_type))
        if start_time is not None:
            stmt = stmt.where(DetectionJob.created_at >= start_time)
        if end_time is not None:
            stmt = stmt.where(DetectionJob.created_at < end_time)

        return self.paginate(
            stmt,
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_columns=JOB_SORT_COLUMNS,
            default_sort=DetectionJob.created_at,
            descending=descending,
        )

    def list_active(self) -> list[DetectionJob]:
        """Return every job that has not reached a terminal state.

        Used at start-up to find jobs left ``pending`` or ``processing`` by a
        process that was killed mid-run. Nothing is going to advance those, so
        they would otherwise sit at partial progress forever and the frontend
        would poll them without end.

        Returns:
            The unfinished jobs, oldest first.
        """
        unfinished = [JobStatus.PENDING.value, JobStatus.PROCESSING.value]
        stmt = (
            select(DetectionJob)
            .where(DetectionJob.status.in_(unfinished))
            .order_by(DetectionJob.created_at.asc())
        )
        return list(self.session.execute(stmt).scalars().all())

    def count_by_status(self) -> dict[str, int]:
        """Return the number of jobs in each lifecycle state.

        Returns:
            A mapping from status name to count, containing an entry for every
            member of :class:`~backend.models.detection.JobStatus` -- zeros
            included, so a caller can index it without a ``get`` default and a
            state that has never occurred still appears in the dashboard.
        """
        stmt = select(DetectionJob.status, func.count()).group_by(DetectionJob.status)
        observed = {str(row[0]): int(row[1] or 0) for row in self.session.execute(stmt).all()}
        return {status.value: observed.get(status.value, 0) for status in JobStatus}

    def count_detections(self, job_id: str) -> int:
        """Return how many plates a job has produced so far.

        Counts through the relationship's foreign key rather than loading the
        job and taking ``len(job.detections)``, so polling the progress of a
        video that has already found hundreds of plates does not load them all
        on every poll.

        Args:
            job_id: Identifier of the job.

        Returns:
            The number of detections attributed to the job.
        """
        # Lazy import to avoid circular dependency
        from backend.models.detection import DetectionHistory

        stmt = (
            select(func.count())
            .select_from(DetectionHistory)
            .where(DetectionHistory.source_job_id == job_id)
        )
        return int(self.session.execute(stmt).scalar_one() or 0)

    # -- State transitions ------------------------------------------------

    def update_progress(
        self,
        job_id: str,
        progress: float | None = None,
        *,
        processed_frames: int | None = None,
        total_frames: int | None = None,
    ) -> DetectionJob | None:
        """Advance a running job's progress.

        Called repeatedly by the background worker. Two behaviours are worth
        knowing about:

        **Progress is clamped, not validated.** The table has a
        ``CHECK (progress BETWEEN 0 AND 1)`` constraint, and floating-point
        frame arithmetic overshoots it routinely -- ``processed / total`` where
        the decoder reports one more frame than the header promised gives
        ``1.0000001``. Raising there would abort a video job at 99% over a
        rounding error, so the value is clamped instead.

        **A terminal job is not modified.** A late progress update arriving
        after the job already failed or was cancelled would drag it back out of
        its final state, and the frontend -- which stops polling on a terminal
        status -- would never see the change. The update is ignored and the job
        returned unchanged.

        When ``progress`` is omitted but both frame counts are known, it is
        derived from them, which keeps the two from disagreeing.

        Args:
            job_id: Identifier of the job to update.
            progress: Completion fraction. Omit to derive it from the frames.
            processed_frames: Frames handled so far.
            total_frames: Revised total, for when the true count is only known
                once decoding starts.

        Returns:
            The updated job, or ``None`` if no job has that identifier. The
            worker treats ``None`` as "the job was deleted underneath me" and
            stops, rather than continuing to process a cancelled upload.
        """
        job = self.get_by_id(job_id)
        if job is None:
            return None
        if job.is_finished:
            return job

        if total_frames is not None:
            job.total_frames = total_frames
        if processed_frames is not None:
            job.processed_frames = max(0, processed_frames)

        if progress is None and job.total_frames:
            progress = job.processed_frames / job.total_frames

        if progress is not None:
            job.progress = min(_PROGRESS_MAX, max(_PROGRESS_MIN, float(progress)))

        if job.status == JobStatus.PENDING.value:
            # The first progress report is proof the worker picked the job up.
            job.status = JobStatus.PROCESSING.value

        self.session.flush()
        return job

    def mark_processing(self, job_id: str) -> DetectionJob | None:
        """Move a job from ``pending`` to ``processing``.

        Args:
            job_id: Identifier of the job.

        Returns:
            The updated job, or ``None`` if it does not exist.
        """
        return self._transition(job_id, JobStatus.PROCESSING)

    def mark_completed(self, job_id: str, *, output_path: str | None = None) -> DetectionJob | None:
        """Mark a job finished successfully.

        Forces ``progress`` to exactly ``1.0``. The worker's last computed
        value is often ``0.998`` because of frame-count rounding, and a
        completed job whose bar is not full looks like a bug to the examiner
        watching the demo.

        Args:
            job_id: Identifier of the job.
            output_path: Where the annotated image or processed video was
                written.

        Returns:
            The updated job, or ``None`` if it does not exist.
        """
        job = self._transition(job_id, JobStatus.COMPLETED)
        if job is None:
            return None
        job.progress = _PROGRESS_MAX
        if output_path is not None:
            job.output_path = output_path
        self.session.flush()
        return job

    def mark_failed(self, job_id: str, error_message: str) -> DetectionJob | None:
        """Mark a job failed and record why, server-side only.

        ``error_message`` is technical English for the log and for support. It
        is deliberately absent from
        :class:`~backend.schemas.detection.DetectionJobResponse`, so storing it
        here cannot leak it to a user (NFR-S4); the user is told the job failed
        through ``status`` plus a generic Vietnamese message.

        Progress is left where it stopped rather than reset, because how far a
        job got before failing is the first thing worth knowing when
        diagnosing it.

        Args:
            job_id: Identifier of the job.
            error_message: Technical description of the failure.

        Returns:
            The updated job, or ``None`` if it does not exist.
        """
        job = self._transition(job_id, JobStatus.FAILED)
        if job is None:
            return None
        job.error_message = error_message
        self.session.flush()
        return job

    def mark_cancelled(self, job_id: str) -> DetectionJob | None:
        """Mark a job cancelled by the user.

        Args:
            job_id: Identifier of the job.

        Returns:
            The updated job, or ``None`` if it does not exist.
        """
        return self._transition(job_id, JobStatus.CANCELLED)

    def _transition(self, job_id: str, status: JobStatus) -> DetectionJob | None:
        """Move a job into a new state, setting ``completed_at`` when terminal.

        Centralising this is what guarantees ``completed_at`` is written for
        every terminal state. Set at three separate call sites, one of them
        eventually would not be, and a job would sit in a finished state with
        no finish time -- which the duration statistics silently skip.

        A job already in a terminal state is returned untouched: a cancel
        arriving just after a failure must not overwrite the failure, or the
        recorded reason for the failure is lost.

        Args:
            job_id: Identifier of the job.
            status: The state to move into.

        Returns:
            The job, or ``None`` if it does not exist.
        """
        job = self.get_by_id(job_id)
        if job is None:
            return None
        if job.is_finished:
            return job

        job.status = status.value
        if status.is_terminal:
            job.completed_at = utcnow()
        self.session.flush()
        return job

    # -- Maintenance ------------------------------------------------------

    def delete_older_than(self, cutoff: dt.datetime) -> int:
        """Delete finished jobs created before a cutoff.

        Their detections go with them through the foreign key's
        ``ON DELETE CASCADE``, which is only enforced because
        :mod:`backend.models.database` switches SQLite's ``foreign_keys``
        pragma on for every connection.

        Only terminal jobs are removed: deleting a job while a worker is still
        writing frames to it would make every subsequent insert fail on the
        foreign key.

        Args:
            cutoff: Jobs created strictly before this instant are removed.

        Returns:
            The number of jobs deleted.
        """
        terminal = [status.value for status in JobStatus if status.is_terminal]
        stmt = select(DetectionJob.id).where(
            DetectionJob.created_at < cutoff,
            DetectionJob.status.in_(terminal),
        )
        job_ids = list(self.session.execute(stmt).scalars().all())
        return self.bulk_delete(job_ids)
