"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Checklist before committing an autogenerated migration:

* Read the generated ``upgrade()``. Autogenerate does not detect a renamed
  column -- it emits a drop plus an add, which destroys the data in it.
* Write ``downgrade()`` by hand if the generated one is empty. A migration that
  cannot be reversed cannot be tested by applying and rolling it back.
* SQLite executes ALTER through batch mode (configured in ``env.py``), which
  rebuilds the table. Named constraints are required for batch mode to be able
  to reproduce them, so never leave a constraint unnamed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

${imports if imports else ""}
# Revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply this migration."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Revert this migration."""
    ${downgrades if downgrades else "pass"}
